import Fonts from '@/components/Fonts';
import ThemeToggle from '@/components/ThemeToggle';
import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <head>
        <Fonts />
      </head>
      <body>
        <StyledComponentsRegistry>
          <ThemeToggle>{children}</ThemeToggle>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
